/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("org.javacord:javacord:3.8.0")
    implementation(project(":utilities"))

    runtimeOnly("org.apache.logging.log4j:log4j-core:2.17.0")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}
